namespace Pliant.Ebnf
{
    public enum EbnfNodeType
    {
        EbnfDefinition,
        EbnfDefinitionConcatenation,
        EbnfBlockRule,
        EbnfBlockSetting,
        EbnfBlockLexerRule,
        EbnfRule,
        EbnfSetting,
        EbnfLexerRule,
        EbnfExpression,
        EbnfExpressionAlteration,
        EbnfTerm,
        EbnfTermConcatenation,
        EbnfFactorIdentifier,
        EbnfFactorLiteral,
        EbnfFactorRegex,
        EbnfFactorOptional,
        EbnfFactorGrouping,
        EbnfFactorRepetition,
        EbnfSettingIdentifier,
        EbnfQualifiedIdentifier,
        EbnfQualifiedIdentifierConcatenation,
        EbnfLexerRuleTerm,
        EbnfLexerRuleTermConcatenation,
        EbnfLexerRuleFactorLiteral,
        EbnfLexerRuleFactorRegex,
        EbnfLexerRuleExpression,
        EbnfLexerRuleExpressionAlteration,
        EbnfExpressionEmpty,
    }
}
